const PRODUCT_IMAGES: Record<string, string> = {
  طماطم: "/images/product/tomato.jfif",
  "طماطم كرزية": "/images/product/tomatocurry.jfif",
  "فلفل أحمر": "/images/product/redpepper.jfif",
  "فلفل أخضر": "/images/product/greenpepper.jfif",
  "فلفل حار": "/images/product/hotpepper.jfif",
  بصل: "/images/product/onion.jfif",
  "بصل أحمر": "/images/product/redonion.jfif",
  "بصل أخضر": "/images/product/greenonion.jfif",
  ثوم: "/images/product/garlic.jfif",
  بطاطا: "/images/product/potato.jfif",
  جزر: "/images/product/carote.jfif",
  خيار: "/images/product/cucumber.jfif",
  باذنجان: "/images/product/eggplant.jfif",
  كوسة: "/images/product/zucchini.jfif",
  قرع: "/images/product/pumpkin.jfif",
  فجل: "/images/product/radish.jfif",
  خس: "/images/product/lettuce.jfif",
  جرجير: "/images/product/watercress.jfif",
  سبانخ: "/images/product/spinach.jfif",
  ملفوف: "/images/product/cabbage.jfif",
  "ملفوف أحمر": "/images/product/redcabbage.jfif",
  بروكلي: "/images/product/broccoli.jfif",
  قرنبيط: "/images/product/cauliflower.jfif",
  كرنب: "/images/product/kronb.jfif",
  "فول أخضر": "/images/product/greenbean.jfif",
  بازلاء: "/images/product/peas.jfif",
  "فاصوليا خضراء": "/images/product/cannellinibean.jfif",
  نعناع: "/images/product/mint.jfif",
  ذرة: "/images/product/corn.jfif",
  تفاح: "/images/product/apple.jfif",
  إجاص: "/images/product/pear.jfif",
  كمثرى: "/images/product/pear.jfif",
  مشمش: "/images/product/apricot.jfif",
  خوخ: "/images/product/peach.jfif",
  كرز: "/images/product/cherry.jfif",
  عنب: "/images/product/grapes.jfif",
  ليمون: "/images/product/lemon.jfif",
  أناناس: "/images/product/ananas.jfif",
  فراولة: "/images/product/strawberry.jfif",
};

export function getProductImageUrl(productName: string): string | undefined {
  return PRODUCT_IMAGES[productName];
}
